### ISSUE TITLE
Compiler incorrectly warns when iterating over AsyncSequence with synchronous implementation 

### ISSUE THREAD

**Issue by saagarjha** [swiftlang/swift#70483]
### Description

When compiling the code below I get warnings:

```console
$ swiftc test.swift
<unknown>:0: warning: no 'async' operations occur within 'await' expression
```

Since this is iterating over an `AsyncSequence` it is not legal to iterate without "await", at least using a for loop. So this should not warn.

### Reproduction

```swift
struct TestSequence: AsyncSequence {
	struct AsyncIterator: AsyncIteratorProtocol {
		var iterator = (1...(.max)).makeIterator()

		mutating func next() -> Element? {
			iterator.next()
		}
	}

	func makeAsyncIterator() -> AsyncIterator {
		AsyncIterator()
	}

	typealias Element = Int
}

let sequence = TestSequence()

var last = 0
var lastTime = ContinuousClock.Instant.now

for await n in sequence where n % 1000 == 0 {
	if ContinuousClock.Instant.now - lastTime > .seconds(1) {
		print(n - last, "iterations per second")
		last = n
		lastTime = ContinuousClock.Instant.now
	}
}
```

### Expected behavior

This should be well-formed code with no warnings.

### Environment

```console
$ swiftc -version
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
```

**Comment by hborla** [comment]
The `AsyncSequence` protocol does not abstract over whether or not concrete types are async or synchronous, and iteration always requires `await`. If you want synchronous iteration, you should use `Sequence` and not `AsyncSequence`. This is correct behavior.

**Comment by saagarjha** [comment]
I feel like the issue I have is slightly different than what you're talking about, but I tested this code in the latest Xcode toolchain and it doesn't produce any warnings anymore, so I guess this is fixed anyways.

**Comment by hborla** [comment]
You're right, I misunderstood what you were saying! I still see warnings though so I'm going to open this issue back up. Perhaps the warnings only appear sometimes
