### ISSUE TITLE
Swift 6: incorrect compiler error when passing a `sending` closure from a global-actor-isolated function

### ISSUE THREAD

**Issue by groue** [swiftlang/swift#74382]
### Description

The Swift 6 compiler that ships with Xcode 16.0 beta (16A5171c) produces an invalid compiler error when the following conditions are met:

- A function accepts a `sending @escaping () -> Void` parameter.
- This function is called from a global-actor isolated function.

### Reproduction

Package.swift

```swift
// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "SwiftIssue",
    platforms: [
        .macOS(.v10_15),
    ],
    products: [
        .library(name: "SwiftIssue", targets: ["SwiftIssue"]),
    ],
    targets: [
        .target(name: "SwiftIssue"),
    ]
)
```

SwiftIssue.swift

```swift
@globalActor actor MyGlobalActor: GlobalActor {
    static let shared = MyGlobalActor()
}

func acceptSendingClosure(completion: sending @escaping () -> Void) { }
func acceptMainActorClosure(completion: @escaping @MainActor () -> Void) { }
func acceptMyGlobalActorClosure(completion: @escaping @MyGlobalActor () -> Void) { }

@MainActor func mainActorIsolatedFunction() {
    // error: main actor-isolated value of type '() -> ()' passed as a
    // strongly transferred parameter; later accesses could race
    acceptSendingClosure { }
    
    acceptMainActorClosure { }     // OK
    acceptMyGlobalActorClosure { } // OK
}

@MyGlobalActor func myGlobalActorIsolatedFunction() {
    // error: global actor 'MyGlobalActor'-isolated value of type '() -> ()'
    // passed as a strongly transferred parameter; later accesses could race
    acceptSendingClosure { }
    
    acceptMainActorClosure { }     // OK
    acceptMyGlobalActorClosure { } // OK
}

actor MyActor {
    func actorIsolatedFunction() {
        acceptSendingClosure { }       // OK
        acceptMainActorClosure { }     // OK
        acceptMyGlobalActorClosure { } // OK
    }
}
```

Build errors:

```
% swift package clean && swift build
Building for debugging...
/Users/groue/Desktop/SwiftIssue/Sources/SwiftIssue/SwiftIssue.swift:12:5: error: main actor-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
10 |     // error: main actor-isolated value of type '() -> ()' passed as a
11 |     // strongly transferred parameter; later accesses could race
12 |     acceptSendingClosure { }
   |     `- error: main actor-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
13 |     
14 |     acceptMainActorClosure { }     // OK

/Users/groue/Desktop/SwiftIssue/Sources/SwiftIssue/SwiftIssue.swift:21:5: error: global actor 'MyGlobalActor'-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
19 |     // error: global actor 'MyGlobalActor'-isolated value of type '() -> ()'
20 |     // passed as a strongly transferred parameter; later accesses could race
21 |     acceptSendingClosure { }
   |     `- error: global actor 'MyGlobalActor'-isolated value of type '() -> ()' passed as a strongly transferred parameter; later accesses could race
22 |     
23 |     acceptMainActorClosure { }     // OK
```

In the Swift 5 language mode, the errors are emitted as warnings:

<details><summary>Variant of Package.swift for reproduction in Swift 5 language mode</summary>

```swift
// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "SwiftIssue",
    platforms: [
        .macOS(.v10_15),
    ],
    products: [
        .library(name: "SwiftIssue", targets: ["SwiftIssue"]),
    ],
    targets: [
        .target(
            name: "SwiftIssue",
            swiftSettings: [
                .enableUpcomingFeature("StrictConcurrency"),
                .enableExperimentalFeature("RegionBasedIsolation"),
                .enableExperimentalFeature("TransferringArgsAndResults"),
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
```

</details>

### Expected behavior

No compiler error in the Swift 6 language mode.

No compiler warning in the Swift 5 language mode.

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

### Additional information

This compiler error is pretty concerning, because **it makes it impossible to call a function that accepts a completion block from a global-actor-isolated function**. Functions with completion blocks **still exist**, and global-actor-isolated functions are **pervasive** in user code.

Please see [this forum post](https://forums.swift.org/t/relaxing-sendable-constraint-to-sending-closures-creates-undesired-warnings/72367) for the initial report, and more information.

**Comment by groue** [comment]
Please find another reproducer below. In this variant the global-actor isolation comes from the enclosing type (also a very frequent pattern in user code):

```swift
@MainActor
struct MainActorIsolatedStruct {
    func mainActorIsolatedFunction() {
        // error: main actor-isolated value of type '() -> ()' passed as a
        // strongly transferred parameter; later accesses could race
        acceptSendingClosure { }
        
        acceptMainActorClosure { }     // OK
        acceptMyGlobalActorClosure { } // OK
    }
}
```

**Comment by hborla** [comment]
In case it wasn't obvious from the link, this is addressed in the second commit of https://github.com/apple/swift/pull/74239

**Comment by hborla** [comment]
Both changes will be cherry picked to `release/6.0`.

**Comment by groue** [comment]
The issue is still present in Xcode 16 beta 2 (same sample code, same output). @hborla, @gottesmm, this is concerning because it lies at the intesection of two important use cases: the global-actor-isolated functions of user code, and the usage of sending in libraries. This bug creates confusion and makes libraries look bad. If I were to ship a GRDB beta right now, people be disappointed and would open issues in the GRDB repo.

**Comment by mattmassicotte** [comment]
@groue  just wanted to let you know that your example code compiles cleanly using swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-22

**Comment by groue** [comment]
The issue is still present in Xcode 16.0 beta 3 (16A5202i) 😢

**Comment by hborla** [comment]
This fix is not included in Xcode 16.0 Beta 3.

**Comment by groue** [comment]
It is in beta 4 🥳
