### ISSUE TITLE
async let + sending doesn't seem to work

### ISSUE THREAD

**Issue by mattmassicotte** [swiftlang/swift#76727]
### Description

I was trying to get around returning a non-Sendable type from a synchronous function. I thought I'd be able to use sending to deal with this, but it doesn't seem to work.

### Reproduction

```swift
class NonSendable {}

@MainActor
func f() async {
	async let x = g()
	// error: non-sendable type 'NonSendable' returned by implicitly asynchronous call to nonisolated function cannot cross actor boundary
	_ = await x
}

func g() -> sending NonSendable {
	NonSendable()
}

await f()
```

### Expected behavior

I would expect this to compile warning-free.

### Environment

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.11 clang-1600.0.26.2)
Target: arm64-apple-macosx14.0

**Comment by mattmassicotte** [comment]
@ktoso Is this actually just a bug? Or does this require a proposal to improve?

**Comment by jamieQ** [comment]
seems like it now compiles on the current main branch snapshots, so maybe just a bug that was fixed?

**Comment by mattmassicotte** [comment]
Wow! I have only tried with the 6.1 snapshots. I just checked 1-23, and it also doesn't fix this. But, yeah seems like just a bug. That's awesome.

**Comment by hborla** [comment]
This was fixed by https://github.com/swiftlang/swift/pull/77900
