### ISSUE TITLE
The main branch windows CI failing (missing mimalloc checkout)

### ISSUE THREAD

**Issue by hjyamauchi** [swiftlang/swift#79115]
### Description

https://ci-external.swift.org/job/swift-main-windows-toolchain/
https://ci-external.swift.org/job/swift-main-windows-toolchain-arm64/

https://ci-external.swift.org/job/swift-main-windows-toolchain/1026/consoleText
```
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\mimalloc\ide\vs2022\mimalloc-lib.vcxproj
Error: Error: MSBuild.exe exited with code 1.
Invocation:
  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\AMD64\MSBuild.exe C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\mimalloc\ide\vs2022\mimalloc-lib.vcxproj -noLogo -maxCpuCount -p:Configuration=Release -p:Platform=x64 -p:OutDir=T:\x64\mimalloc\bin\ -p:VCRedistDir=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Redist\\MSVC\\14.38.33135\\x64\\Microsoft.VC143.CRT\\ -p:IntDir=T:\x64\mimalloc\mimalloc\
Call stack:
  at Invoke-Program, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 591
  at Build-mimalloc, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 1716
  at Invoke-BuildStep, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 413
  at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 3106

    at Invoke-Program, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 595
    at Build-mimalloc, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 1716
    at Invoke-BuildStep, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 413
    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 3106
  From System.Management.Automation.RuntimeException: Error: MSBuild.exe exited with code 1.
  Invocation:
    C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\AMD64\MSBuild.exe C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\mimalloc\ide\vs2022\mimalloc-lib.vcxproj -noLogo -maxCpuCount -p:Configuration=Release -p:Platform=x64 -p:OutDir=T:\x64\mimalloc\bin\ -p:VCRedistDir=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Redist\\MSVC\\14.38.33135\\x64\\Microsoft.VC143.CRT\\ -p:IntDir=T:\x64\mimalloc\mimalloc\
  Call stack:
    at Invoke-Program, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 591
    at Build-mimalloc, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 1716
    at Invoke-BuildStep, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 413
    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\swift\utils\build.ps1: line 3106
 ```

I think that the root cause is the fact that the mimalloc repo isn't added to the dependencies (it's not checked out during the build).

Revert https://github.com/swiftlang/swift/pull/79112
Probably this needs to be reverted as well: https://github.com/swiftlang/swift-installer-scripts/pull/371

CC @shahmishal @compnerd @weliveindetail 

### Reproduction

CI

### Expected behavior

No failure

### Environment

CI

**Comment by hjyamauchi** [comment]
@shahmishal can you add the mimalloc repo https://github.com/microsoft/mimalloc to a dependency of the windows toolchain builds on the ci-external.swift.org CIs?

**Comment by shahmishal** [comment]
This is now fixed, I just updated the CI config.

**Comment by weliveindetail** [comment]
Unfortunately, it still fails: https://ci-external.swift.org/job/swift-main-windows-toolchain/1029/
```
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\mimalloc\ide\vs2022\mimalloc-lib.vcxproj
Error: Error: MSBuild.exe exited with code 1.
Invocation:
  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\AMD64\MSBuild.exe 
  C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\mimalloc\ide\vs2022\mimalloc-lib.vcxproj 
  -noLogo -maxCpuCount -p:Configuration=Release -p:Platform=x64 -p:OutDir=T:\x64\mimalloc\bin\ 
  -p:VCRedistDir=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Redist\\MSVC\\14.38.33135\\x64\\Microsoft.VC143.CRT\\
  -p:IntDir=T:\x64\mimalloc\mimalloc\
```

**Comment by weliveindetail** [comment]
@shahmishal Should I land the revert linked above?

**Comment by weliveindetail** [comment]
mimalloc seems to be available now on the mainline build bots:
```
Cloning repository https://github.com/microsoft/mimalloc.git
 > git init C:\Users\swift-ci\jenkins\workspace\swift-main-windows-toolchain\mimalloc # timeout=10
https://ci-external.swift.org/job/swift-main-windows-toolchain/1030
```

PRs https://github.com/swiftlang/swift/pull/79151 and https://github.com/swiftlang/swift-installer-scripts/pull/381 are about to re-land.
