### ISSUE TITLE
Assertion failed: (!Name || (Name.getArgumentNames().size() == BodyParams->size())), function setParameters, file Decl.cpp, line 10212.

### ISSUE THREAD

**Issue by shahmishal** [swiftlang/swift#79255]
### Description

Six test failures with Xcode 16.2 

```
  Swift-validation(macosx-arm64) :: IDE/complete_from_cocoa.swift
  Swift-validation(macosx-arm64) :: IDE/complete_from_cocoa_2.swift
  Swift-validation(macosx-arm64) :: IDE/complete_repl_from_cocoa.swift
  Swift-validation(macosx-arm64) :: IDE/complete_sdk_platform.swift
  Swift-validation(macosx-arm64) :: Sema/SwiftUI/rdar57201781.swift
  Swift-validation(macosx-arm64) :: Sema/SwiftUI/rdar70880670.swift
```

```
FAIL: Swift-validation(macosx-arm64) :: Sema/SwiftUI/rdar57201781.swift (12163 of 18778)
******************** TEST 'Swift-validation(macosx-arm64) :: Sema/SwiftUI/rdar57201781.swift' FAILED ********************
Exit Code: 134

Command Output (stderr):
--
RUN: at line 1: /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend -target arm64-apple-macosx13.0  -module-cache-path /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/swift-test-results/arm64-apple-macosx13.0/clang-module-cache -sdk '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk'  -swift-version 4  -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999' -define-availability 'SwiftStdlib 6.2:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999'  -typo-correction-limit 10  -typecheck -verify -disable-objc-attr-requires-foundation-module /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/swift/validation-test/Sema/SwiftUI/rdar57201781.swift -target arm64-apple-macosx10.15 -swift-version 5
+ /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend -target arm64-apple-macosx13.0 -module-cache-path /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/swift-test-results/arm64-apple-macosx13.0/clang-module-cache -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -swift-version 4 -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999' -define-availability 'SwiftStdlib 6.2:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999' -typo-correction-limit 10 -typecheck -verify -disable-objc-attr-requires-foundation-module /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/swift/validation-test/Sema/SwiftUI/rdar57201781.swift -target arm64-apple-macosx10.15 -swift-version 5
Assertion failed: (!Name || (Name.getArgumentNames().size() == BodyParams->size())), function setParameters, file Decl.cpp, line 10212.
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend -target arm64-apple-macosx13.0 -module-cache-path /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/swift-test-results/arm64-apple-macosx13.0/clang-module-cache -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk -swift-version 4 -define-availability "SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999" -define-availability "SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2" -define-availability "SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0" -define-availability "SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4" -define-availability "SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0" -define-availability "SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5" -define-availability "SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0" -define-availability "SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4" -define-availability "SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0" -define-availability "SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4" -define-availability "SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0" -define-availability "SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1" -define-availability "SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0" -define-availability "SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -define-availability "SwiftStdlib 6.2:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999" -typo-correction-limit 10 -typecheck -verify -disable-objc-attr-requires-foundation-module /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/swift/validation-test/Sema/SwiftUI/rdar57201781.swift -target arm64-apple-macosx10.15 -swift-version 5
1.	Apple Swift version 6.2-dev (LLVM 5e1f334a6b85c74, Swift 022596473f967d7)
2.	Compiling with effective version 5.10
3.	While evaluating request TypeCheckSourceFileRequest(source_file "/Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/swift/validation-test/Sema/SwiftUI/rdar57201781.swift")
4.	While evaluating request TypeCheckFunctionBodyRequest(rdar57201781.(file).ContentView._@/Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/swift/validation-test/Sema/SwiftUI/rdar57201781.swift:11:23)
5.	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGColorConversionInfo.h:71:47: importing 'CGColorConversionInfoCreateForToneMapping'
/Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/validation-test-macosx-arm64/Sema/SwiftUI/Output/rdar57201781.swift.script: line 1: 39223 Abort trap: 6           /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/bin/swift-frontend -target arm64-apple-macosx13.0 -module-cache-path /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/build/buildbot_incremental/swift-macosx-arm64/swift-test-results/arm64-apple-macosx13.0/clang-module-cache -sdk '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk' -swift-version 4 -define-availability 'SwiftStdlib 9999:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999' -define-availability 'SwiftStdlib 5.0:macOS 10.14.4, iOS 12.2, watchOS 5.2, tvOS 12.2' -define-availability 'SwiftStdlib 5.1:macOS 10.15, iOS 13.0, watchOS 6.0, tvOS 13.0' -define-availability 'SwiftStdlib 5.2:macOS 10.15.4, iOS 13.4, watchOS 6.2, tvOS 13.4' -define-availability 'SwiftStdlib 5.3:macOS 11.0, iOS 14.0, watchOS 7.0, tvOS 14.0' -define-availability 'SwiftStdlib 5.4:macOS 11.3, iOS 14.5, watchOS 7.4, tvOS 14.5' -define-availability 'SwiftStdlib 5.5:macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0' -define-availability 'SwiftStdlib 5.6:macOS 12.3, iOS 15.4, watchOS 8.5, tvOS 15.4' -define-availability 'SwiftStdlib 5.7:macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0' -define-availability 'SwiftStdlib 5.8:macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4' -define-availability 'SwiftStdlib 5.9:macOS 14.0, iOS 17.0, watchOS 10.0, tvOS 17.0' -define-availability 'SwiftStdlib 5.10:macOS 14.4, iOS 17.4, watchOS 10.4, tvOS 17.4, visionOS 1.1' -define-availability 'SwiftStdlib 6.0:macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0' -define-availability 'SwiftStdlib 6.1:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999' -define-availability 'SwiftStdlib 6.2:macOS 9999, iOS 9999, watchOS 9999, tvOS 9999, visionOS 9999' -typo-correction-limit 10 -typecheck -verify -disable-objc-attr-requires-foundation-module /Users/ec2-user/jenkins/workspace/oss-swift-pr-test-macos-arm64/swift/validation-test/Sema/SwiftUI/rdar57201781.swift -target arm64-apple-macosx10.15 -swift-version 5

--

********************
```

### Reproduction

```swift

```

### Expected behavior

```
./swift/utils/build-script --preset=buildbot_all_platforms,tools=RA,stdlib=RA install_destdir=install installable_package=oss-swift-pr-test-macos-arm64-b3.tar.gz
```

### Environment

Xcode 16.2 + macOS 15.2

**Comment by hamishknight** [comment]
IIRC this is fixed by https://github.com/swiftlang/swift/pull/78124, cc @beccadax

**Comment by bnbarham** [comment]
Re-enabling the completion tests in https://github.com/swiftlang/swift/pull/79950, I believe the other two are still failing for other reasons though (too long to typecheck).
