### ISSUE TITLE
Swift Compiler crash with isolated deinit

### ISSUE THREAD

**Issue by fritzt0** [swiftlang/swift#82523]
### Description

The Swift compiler in Xcode 16 beta 1 & 2 crashes when targeting iOS with the following code:

```
import UIKit

class MyView: UIView {
  isolated deinit {}
}
```

More examples without the involvement of UIKit are shown in the [Swift forum thread](https://forums.swift.org/t/swift-6-2-ready-for-isolated-deinit/)

I’m very grateful for any solution.

### Reproduction

```
import UIKit

class MyView: UIView {
  isolated deinit {}
}
```

### Stack dump

```text
1.	Apple Swift version 6.2 (swiftlang-6.2.0.10.950 clang-1700.3.10.950)
2.	Compiling with effective version 5.10
3.	While evaluating request ASTLoweringRequest(Lowering AST to SIL for module IsoDeinitCrash)
4.	While silgen emitDestructor -dealloc SIL function "@$s14IsoDeinitCrash6MyViewCfZ".
 for 'deinit' (at /Users/fritter/Temp/IsoDeinitCrash/IsoDeinitCrash/IsoDeinitCrash.swift:11:12)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010717b450 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000107178de0 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x000000010717ba7c SignalHandler(int, __siginfo*, void*) + 344
3  libsystem_platform.dylib 0x000000019f460624 _sigtramp + 56
4  swift-frontend           0x00000001019419c8 swift::Lowering::SILGenFunction::emitObjCDestructor(swift::SILDeclRef) + 468
5  swift-frontend           0x00000001019419c8 swift::Lowering::SILGenFunction::emitObjCDestructor(swift::SILDeclRef) + 468
6  swift-frontend           0x00000001018c2bdc swift::Lowering::SILGenModule::emitDeallocatorImpl(swift::SILDeclRef, swift::SILFunction*) + 1484
7  swift-frontend           0x00000001018c16c0 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 5656
8  swift-frontend           0x00000001018c45b0 swift::Lowering::SILGenModule::emitObjCAllocatorDestructor(swift::ClassDecl*, swift::DestructorDecl*) + 152
9  swift-frontend           0x00000001018c4b8c swift::Lowering::SILGenModule::emitDestructor(swift::ClassDecl*, swift::DestructorDecl*) + 564
10 swift-frontend           0x0000000101a22b14 (anonymous namespace)::SILGenType::emitType() + 568
11 swift-frontend           0x00000001018bfda8 swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 100
12 swift-frontend           0x00000001018c6c1c swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 2364
13 swift-frontend           0x0000000101a09e80 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>> (swift::ASTLoweringDescriptor), (swift::RequestFlags)17>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 208
14 swift-frontend           0x00000001018cb6a4 swift::ASTLoweringRequest::OutputType swift::Evaluator::getResultUncached<swift::ASTLoweringRequest, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()>(swift::ASTLoweringRequest const&, swift::ASTLoweringRequest::OutputType swift::evaluateOrFatal<swift::ASTLoweringRequest>(swift::Evaluator&, swift::ASTLoweringRequest)::'lambda'()) + 572
15 swift-frontend           0x0000000100de8580 swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 2616
16 swift-frontend           0x0000000100deb274 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1764
17 swift-frontend           0x0000000100de9e90 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3580
18 swift-frontend           0x0000000100d6b444 swift::mainEntry(int, char const**) + 5412
19 dyld                     0x000000019f086b98 start + 6076
```

### Expected behavior

no crash

### Environment

swift-driver version: 1.127.5.3 Apple Swift version 6.2 (swiftlang-6.2.0.10.950 clang-1700.3.10.950)
Target: arm64-apple-macosx15.0

Xcode 16 beta 2 on macOS 15.5

**Comment by ktoso** [comment]
I was able to reproduce this:

The problem seems to be that in `emibObjCDestructor` the 
```
-> 737 	  emitProfilerIncrement(dd->getTypecheckedBody());
```

type checked body is `null`, 

for a destructor like 

```
(destructor_decl decl_context=0x13d1ab228 range=[/tmp/TestMe/TestMe/main.swift:13:14 - line:14:5] "deinit" interface_type="(Bar) -> () -> ()" access=internal
  (isolated_attr range=[/tmp/TestMe/TestMe/main.swift:13:5 - line:13:5])
  (raw_doc_comment_attr comment_range=[/tmp/TestMe/TestMe/main.swift:12:36 - line:12:44] RangeText="// crash")
  (parameter "self" decl_context=0x1330087e8) thrown_type="<null>"
  (parameter_list))
```

I've not dug into why that is yet.

**Comment by DougGregor** [comment]
It's specific to Swift module file generation, where we are trying to emit the destructor implementation even though we're supposed to skip it.

**Comment by DougGregor** [comment]
Fix landed on the 6.2 branch, and will merge to main soon. Closing!

**Comment by fritzt0** [comment]
It still crashes when using Xcode 26 beta 3, Apple Swift version 6.2 (swiftlang-6.2.0.13.10 clang-1700.3.13.4). Did the fix not make it into the release?

**Comment by DougGregor** [comment]
It did not make it into beta 3. There's a bit of lag between commits here on GitHub and the compiler that ships in a given Xcode.

**Comment by fritzt0** [comment]
Good to know, thanks!

**Comment by lyzkov** [comment]
The crash is still apparent on Xcode 26.2.

**Comment by DougGregor** [comment]
> The crash is still apparent on Xcode 26.2.

I suspect it's something different; this fix made it into Xcode 26. Can you open another issue with a reproducer?

**Comment by couchdeveloper** [comment]
I experienced this issue as well. Debug build are building OK; a Release build fails 
My workaround is this: 

```swift
    @_optimize(none)
    isolated deinit {
        cancel()
    }
```

There's a chance it's not just related to `isolated`.

**Console output**

```console 
1.	Apple Swift version 6.3.2 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
2.	Compiling with the current language version
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { PrepareOptimizationPasses, EarlyModulePasses, HighLevel,Function+EarlyLoopOpt, HighLevel,Module+StackPromote, MidLevel,Function, ClosureSpecialize, LowLevel,Function, LateLoopOpt, SIL Debug Info Generator } on SIL for EffectView)
4.	While running pass #4079 SILFunctionTransform "EarlyPerfInliner" on SILFunction "@$s10EffectView0A10ObservableCfD".
 for 'deinit' (at /Users/agrosam/Developer/EffectView Project/EffectView/Sources/EffectView/EffectObservable/EffectObservable.swift:88:14)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x000000010aa78a30 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x000000010aa75ed0 llvm::sys::RunSignalHandlers() + 172
2  swift-frontend           0x000000010aa79020 SignalHandler(int, __siginfo*, void*) + 356
3  libsystem_platform.dylib 0x000000018e9e97a4 _sigtramp + 56
4  swift-frontend           0x0000000105707158 isCallerAndCalleeLayoutConstraintsCompatible(swift::FullApplySite) + 236
... 
```


I can provide more information if requested.
