### ISSUE TITLE
Xcode 26 beta 4 crash

### ISSUE THREAD

**Issue by poshmarkyqi** [swiftlang/swift#83528]
### Description

Compiling a project with the Xcode 26 beta 4 `SWIFT_OPTIMIZATION_LEVEL = "-Owholemodule"` gives me this compiler failure, which asked me to file a report.
when `SWIFT_OPTIMIZATION_LEVEL = "-Onone"` in debug mode there is no compiler error

### Reproduction

compile with `SWIFT_OPTIMIZATION_LEVEL = "-Owholemodule"`

### Stack dump

```text
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
0.	Program arguments: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -filelist /var/folders/fl/1nmjfnb90jg6rzxr50ptchhr0000gn/T/TemporaryDirectory.sgDF7c/sources-1 -supplementary-output-file-map /var/folders/fl/1nmjfnb90jg6rzxr50ptchhr0000gn/T/TemporaryDirectory.sgDF7c/supplementaryOutputs-1 -target arm64-apple-ios16.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -stack-check -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS26.0.sdk -I /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PackageFrameworks -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos -F /Users/yangfanqi/Documents/ios/Libraries/Iovation -F /Users/yangfanqi/Documents/ios/Libraries/MiSnap -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Adyen -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/AdyenNetworking -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/AffirmSDK -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/AppAuth -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Atributika -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Braintree -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/BranchSDK -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Charts -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/DTCoreText -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/DTFoundation -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseABTesting -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCore -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCoreExtension -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCoreInternal -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCrashlytics -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseInstallations -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebasePerformance -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseRemoteConfig -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseRemoteConfigInterop -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseSessions -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseSharedSwift -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GTMAppAuth -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GTMSessionFetcher -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GoogleDataTransport -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GoogleSignIn -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GoogleUtilities -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/MBProgressHUD -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PromisesObjC -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PromisesSwift -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/RxCocoa -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/RxRelay -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/RxSwift -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Sift -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/SwiftAlgorithms -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/lottie-ios -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/nanopb -F /Users/yangfanqi/Documents/ios/Pods/Adyen3DS2/XCFramework/Dynamic -F /Users/yangfanqi/Documents/ios/Pods/AgoraRtcEngine_Special_iOS -F /Users/yangfanqi/Documents/ios/Pods/AgoraRtm_Special_iOS -F /Users/yangfanqi/Documents/ios/Pods/AppsFlyerFramework/binaries/xcframework/full -F /Users/yangfanqi/Documents/ios/Pods/Braintree/Frameworks/XCFrameworks -F /Users/yangfanqi/Documents/ios/Pods/FBAEMKit/XCFrameworks -F /Users/yangfanqi/Documents/ios/Pods/FBSDKCoreKit/XCFrameworks -F /Users/yangfanqi/Documents/ios/Pods/FBSDKCoreKit_Basics/XCFrameworks -F /Users/yangfanqi/Documents/ios/Pods/FBSDKLoginKit/XCFrameworks -F /Users/yangfanqi/Documents/ios/Pods/FBSDKShareKit/XCFrameworks -F /Users/yangfanqi/Documents/ios/Pods/FirebaseAnalytics/Frameworks -F /Users/yangfanqi/Documents/ios/Pods/GoogleAnalytics/Frameworks -F /Users/yangfanqi/Documents/ios/Pods/GoogleAppMeasurement/Frameworks -F /Users/yangfanqi/Documents/ios/Pods/GoogleTagManager/Frameworks -F /Users/yangfanqi/Documents/ios/Pods/MiSnap/MiSnap -F /Users/yangfanqi/Documents/ios/Pods/MiSnapAssetManager/MiSnapAssetManager -F /Users/yangfanqi/Documents/ios/Pods/MiSnapCore/MiSnapCore -F /Users/yangfanqi/Documents/ios/Pods/MiSnapFacialCapture/MiSnapFacialCapture -F /Users/yangfanqi/Documents/ios/Pods/MiSnapFacialCaptureUX/MiSnapFacialCaptureUX -F /Users/yangfanqi/Documents/ios/Pods/MiSnapUX/MiSnapUX -F /Users/yangfanqi/Documents/ios/Pods/Rokt-Widget -F /Users/yangfanqi/Documents/ios/Pods/SnapSDK -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/Adyen3DS2 -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AgoraRtcEngine_Special_iOS -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AgoraRtm_Special_iOS -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/AppsFlyerFramework/Main -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/Braintree/DataCollector -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBAEMKit -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBSDKCoreKit -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBSDKCoreKit_Basics -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBSDKLoginKit -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FBSDKShareKit -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/FirebaseAnalytics/AdIdSupport -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleAnalytics -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/AdIdSupport -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleAppMeasurement/WithoutAdIdSupport -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/GoogleTagManager -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MiSnap -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MiSnapAssetManager -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MiSnapCore -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MiSnapFacialCapture -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MiSnapFacialCaptureUX -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/MiSnapUX -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/Rokt-Widget -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/SnapSDK/SCSDKCoreKit -F /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/SnapSDK/SCSDKCreativeKit -F /Users/yangfanqi/Documents/ios/Libraries/Iovation -no-color-diagnostics -Xcc -fno-color-diagnostics -g -debug-info-format=dwarf -dwarf-version=4 -module-cache-path /Users/yangfanqi/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -O -D PRODUCT_ENV_PRODUCTION_RC -D COCOAPODS -new-driver-path /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -serialize-debugging-options -load-plugin-executable /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/UninstalledProducts/macosx/DependenciesMacrosPlugin#DependenciesMacrosPlugin -const-gather-protocols-file /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/Objects-normal/arm64/PM-RC_const_extract_protocols.json -enable-experimental-feature DebugDescriptionMacro -enable-bare-slash-regex -strict-concurrency=targeted -empty-abi-descriptor -Xcc -working-directory -Xcc /Users/yangfanqi/Documents/ios -file-compilation-dir /Users/yangfanqi/Documents/ios -Xcc -ivfsstatcache -Xcc /Users/yangfanqi/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos26.0-23A5297f-6e34d0abcd5d556b4ff52abc730e661d.sdkstatcache -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/PM-RC-generated-files.hmap -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/PM-RC-own-target-headers.hmap -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/PM-RC-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/Poshmark-47cc268c5ce6b7239e742e5aa9ee6f3e-VFS-iphoneos/all-product-headers.yaml -Xcc -iquote -Xcc /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/PM-RC-project-headers.hmap -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Adyen/Adyen.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/AdyenNetworking/AdyenNetworking.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/AffirmSDK/AffirmSDK.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/AppAuth/AppAuth.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Atributika/Atributika.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Braintree/Braintree.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/BranchSDK/BranchSDK.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Charts/Charts.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/DTCoreText/DTCoreText.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/DTFoundation/DTFoundation.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseABTesting/FirebaseABTesting.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCore/FirebaseCore.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCoreExtension/FirebaseCoreExtension.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCoreInternal/FirebaseCoreInternal.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseCrashlytics/FirebaseCrashlytics.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseInstallations/FirebaseInstallations.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebasePerformance/FirebasePerformance.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseRemoteConfig/FirebaseRemoteConfig.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseRemoteConfigInterop/FirebaseRemoteConfigInterop.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseSessions/FirebaseSessions.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/FirebaseSharedSwift/FirebaseSharedSwift.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GTMAppAuth/GTMAppAuth.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GTMSessionFetcher/GTMSessionFetcher.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GoogleDataTransport/GoogleDataTransport.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GoogleSignIn/GoogleSignIn.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/GoogleUtilities/GoogleUtilities.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/MBProgressHUD/MBProgressHUD.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PromisesObjC/FBLPromises.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/PromisesSwift/Promises.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/RxCocoa/RxCocoa.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/RxRelay/RxRelay.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/RxSwift/RxSwift.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/Sift/Sift.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/SwiftAlgorithms/Algorithms.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/lottie-ios/Lottie.framework/Headers -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/BuildProductsPath/Release-iphoneos/nanopb/nanopb.framework/Headers -Xcc -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS26.0.sdk/usr/include/libxml2 -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/DerivedSources-normal/arm64 -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/DerivedSources/arm64 -Xcc -I/Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/IntermediateBuildFilesPath/Poshmark.build/Release-iphoneos/PM-RC.build/DerivedSources -Xcc -DNS_BLOCK_ASSERTIONS -Xcc -DCONFIGURATION_Release -Xcc -DCOCOAPODS=1 -Xcc -DNS_BLOCK_ASSERTIONS -Xcc -DCONFIGURATION_Release -Xcc -DNS_BLOCK_ASSERTIONS -Xcc -DCONFIGURATION_Release -Xcc -DPB_FIELD_32BIT=1 -Xcc -DPB_NO_PACKED_STRUCTS=1 -Xcc -DPB_ENABLE_MALLOC=1 -Xcc -DPRODUCT_ENV_PRODUCTION_RC -import-objc-header /Users/yangfanqi/Documents/ios/App/SupportingFiles/Poshmark-Bridging-Header.h -pch-output-dir /Users/yangfanqi/Library/Developer/Xcode/DerivedData/Poshmark-cjyecmmralttpbdxdkvfqpyavmsl/Build/Intermediates.noindex/ArchiveIntermediates/PM-RC/PrecompiledHeaders -no-auto-bridging-header-chaining -module-name PM_RC -disable-clang-spi -target-sdk-version 26.0 -target-sdk-name iphoneos26.0 -external-plugin-path /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib/swift/host/plugins#/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -external-plugin-path /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/local/lib/swift/host/plugins#/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/swift-plugin-server -in-process-plugin-server-path /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/libSwiftInProcPluginServer.dylib -plugin-path /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/host/plugins -plugin-path /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/lib/swift/host/plugins -enable-default-cmo -num-threads 12 -output-filelist /var/folders/fl/1nmjfnb90jg6rzxr50ptchhr0000gn/T/TemporaryDirectory.sgDF7c/outputs-1 -index-unit-output-path-filelist /var/folders/fl/1nmjfnb90jg6rzxr50ptchhr0000gn/T/TemporaryDirectory.sgDF7c/index-unit-outputs-1
1.	Apple Swift version 6.2 (swiftlang-6.2.0.14.8 clang-1700.3.14.6)
2.	Compiling with effective version 5.10
3.	While evaluating request ExecuteSILPipelineRequest(Run pipelines { PrepareOptimizationPasses, EarlyModulePasses, HighLevel,Function+EarlyLoopOpt, HighLevel,Module+StackPromote, MidLevel,Function, ClosureSpecialize, LowLevel,Function, LateLoopOpt, SIL Debug Info Generator } on SIL for PM_RC)
4.	While running pass #1745610 SILFunctionTransform "CopyPropagation" on SILFunction "@$s5PM_RC14PriceFormFieldC8currency10isOptional20accessibilityContextAcA8CurrencyV_SbAA017BaseAccessibilityJ0CSgtcfc".
 for 'init(currency:isOptional:accessibilityContext:)' (at /Users/yangfanqi/Documents/ios/App/ViewModels/Forms/FormFields/PriceFormField.swift:17:5)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000106806bd0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000106804560 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x00000001068071fc SignalHandler(int, __siginfo*, void*) + 344
3  libsystem_platform.dylib 0x00000001885dc624 _sigtramp + 56
4  libsystem_pthread.dylib  0x00000001885a288c pthread_kill + 296
5  libsystem_c.dylib        0x00000001884abc60 abort + 124
6  swift-frontend           0x000000010082a0a4 swift::DiagnosticHelper::~DiagnosticHelper() + 0
7  swift-frontend           0x0000000106774d10 llvm::report_fatal_error(llvm::Twine const&, bool) + 280
8  swift-frontend           0x0000000106774bf8 llvm::report_fatal_error(llvm::Twine const&, bool) + 0
9  swift-frontend           0x0000000100e9f350 swift::LinearLifetimeChecker::ErrorBuilder::handleError(llvm::function_ref<void ()>&&, bool) const + 684
10 swift-frontend           0x0000000100eac9e4 verifySILValueHelper(swift::SILFunction const*, swift::SILValue, swift::LinearLifetimeChecker::ErrorBuilder&, swift::DeadEndBlocks*, swift::GuaranteedPhiVerifier&) + 6076
11 swift-frontend           0x0000000100eacf08 swift::SILFunction::verifyOwnership(swift::DeadEndBlocks*) const + 768
12 swift-frontend           0x00000001014299b0 (anonymous namespace)::CopyPropagation::run() + 9032
13 swift-frontend           0x00000001013971d4 swift::SILPassManager::runFunctionPasses(unsigned int, unsigned int) + 3556
14 swift-frontend           0x0000000101390484 swift::SILPassManager::executePassPipelinePlan(swift::SILPassPipelinePlan const&) + 200
15 swift-frontend           0x00000001013b6008 swift::SimpleRequest<swift::ExecuteSILPipelineRequest, std::__1::tuple<> (swift::SILPipelineExecutionDescriptor), (swift::RequestFlags)1>::evaluateRequest(swift::ExecuteSILPipelineRequest const&, swift::Evaluator&) + 52
16 swift-frontend           0x0000000101399dc4 swift::ExecuteSILPipelineRequest::OutputType swift::Evaluator::getResultUncached<swift::ExecuteSILPipelineRequest, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'()>(swift::ExecuteSILPipelineRequest const&, swift::ExecuteSILPipelineRequest::OutputType swift::evaluateOrFatal<swift::ExecuteSILPipelineRequest>(swift::Evaluator&, swift::ExecuteSILPipelineRequest)::'lambda'()) + 412
17 swift-frontend           0x000000010139c8f0 swift::runSILOptimizationPasses(swift::SILModule&) + 448
18 swift-frontend           0x00000001008467cc swift::CompilerInstance::performSILProcessing(swift::SILModule*) + 1148
19 swift-frontend           0x000000010044c170 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1360
20 swift-frontend           0x000000010044bacc swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 2680
21 swift-frontend           0x000000010044e78c performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1764
22 swift-frontend           0x000000010044d39c swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 3580
23 swift-frontend           0x00000001003cea24 swift::mainEntry(int, char const**) + 5412
24 dyld                     0x0000000188202b98 start + 6076
```

### Expected behavior

This project compiles and archive successfully with Xcode 16.4

### Environment

swift-driver version: 1.127.10 Apple Swift version 6.2 (swiftlang-6.2.0.14.8 clang-1700.3.14.6)
Target: arm64-apple-macosx15.0

**Comment by tbkka** [comment]
It's very rare that we can diagnose a compiler crash like this without an actual project that we can compile to reproduce the error.

At a minimum, did you try simple "-O" optimization?  This doesn't look like it would be related to whole-module optimization.

**Comment by poshmarkyqi** [comment]
I have tested "-O" optimization also and it seems like it has the same issue `error: compile command failed due to signal 6`
I also want to add "-Osize" option seems to be fine.

**Comment by atrick** [comment]
This may have been fixed on main. For example:

---
commit 05fcf5fbbc8108afefc254c2120f9a85b4e97ea1
Author: Andrew Trick <atrick@apple.com>
Date:   Tue Jul 29 11:03:40 2025

    Fix OSSA RAUW utility for move_value that changes ownership.
    Fixes rdar://156431548 Error! Found a leaked owned value that was never consumed.
---

The only way to be sure is to try with a development snapshot from the main branch.
https://www.swift.org/install/macos/

**Comment by poshmarkyqi** [comment]
I want to add the latest Xcode beta 6 still have the same issue.

**Comment by atrick** [comment]
The fix I mentioned above is not in Xcode yet. You would need to download an open source toolchain from swift.org.

Alternatively, you may be able to suppress this assertion by adding OTHER_SWIFT_FLAGS="-Xfrontend -sil-verify-none"

**Comment by serajahmad01** [comment]
Facing the similar issue in Xcode 26.0 release version as well while archiving for Release configuration.
If i change the SWIFT_OPTIMIZATION_LEVEL to "-Onone", it is working fine.

**Comment by ikeval** [comment]
I am not getting a crash but archive fails after i updated project to Swift 6 and turned on all the concurrency flags. It builds and runs fine but upon archiving getting the same error. 

Also, tried to use the fix this using the @atrick suggestion but it gave me an error.
error: Driver threw unknown argument: '-Xfrontend -sil-verify-none' without emitting errors.

It does archive with changing the optimization level but i don't feel like doing that.  

Edit:
Upon further inspection of the build log, it seems one of my class is problematic. The error in log points to line `final class Navigator<Screen: Hashable & View> {` and below is the full class info. I am not sure what I am doing wrong here. 
```swift
@Observable
final class Navigator<Screen: Hashable & View> {
    var path: [Screen] = []

    func navigate(to screen: Screen) {
        path.append(screen)
    }

    func popToRoot() {
        path = []
    }
}
```

**Comment by Estremadoyro** [comment]
> Facing the similar issue in Xcode 26.0 release version as well while archiving for Release configuration. If i change the SWIFT_OPTIMIZATION_LEVEL to "-Onone", it is working fine.

this guy fucks, it worked for me tyyy

**Comment by filipkowicz** [comment]
tip from my side. I was able to track down exact line which caused issues with reproducing crash locally - with archive action on xcode - then going thru compiler crash stacktrace which is available in build log. and it turned out that it was:

`fatalError("some \(interpolated) string")` and simple change to `fatalError("const string")` fixed compiler issue
