### ISSUE TITLE
KeyPaths are still not properly Sendable in Swift 6.2

### ISSUE THREAD

**Issue by mattneub** [swiftlang/swift#84983]
### Description

I feel that https://github.com/swiftlang/swift-evolution/blob/main/proposals/0418-inferring-sendable-for-methods.md hasn't done its job. KeyPaths that are clearly Sendable are being marked as not Sendable, and if you explicit try to mark them as Sendable, they become unusable.

The problem arises for me particularly in conjunction with the SortComparator protocol, which is useful when you want to combine multiple sort criteria for sorting an array.

I'm using Xcode 26.0.1 (17A400) in a project with Swift 6 turned on, with the usual approachable concurrency and default main actor isolation (and, of course, the upcoming features turned on, including key path inference).

### Reproduction

Here's my existing code, reduced into a simple iOS view controller file:

```swift
import UIKit

struct Person {
    let firstName: String
    let lastName: String
}

struct PersonStringComparator: SortComparator {
    let keyPath: KeyPath<Person, String> // WARNING
    var order: SortOrder
    init(_ keyPath: KeyPath<Person, String>, order: SortOrder = .forward) {
        self.keyPath = keyPath
        self.order = order
    }
    func compare(_ lhs: Person, _ rhs: Person) -> ComparisonResult {
        let options: String.CompareOptions = order == .forward ? [] : [.backwards]
        return lhs[keyPath: keyPath].compare(rhs[keyPath: keyPath], options: options)
    }
}

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        // elsewhere
        var array: [Person] = [
            .init(firstName: "Harpo", lastName: "Marx"),
            .init(firstName: "Groucho", lastName: "Marx"),
            .init(firstName: "Groucho", lastName: "Aardvark")
        ]
        let comparisons: [PersonStringComparator] = [.init(\.lastName), .init(\.firstName)]
        array.sort(using: comparisons)
    }
}

/*
 WARNING:
Stored property 'keyPath' of 'Sendable'-conforming struct 'PersonStringComparator'
 has non-Sendable type 'KeyPath<Person, String>'
 Generic class 'KeyPath' does not conform to the 'Sendable' protocol
 */
```

Note the warning on the second line of PersonStringComparator; I've copied and pasted the content of the warning at the bottom of the code.

If you try to make the warning go away by explicitly marking the key path as sendable, things get even worse:

```swift
import UIKit

struct Person {
    let firstName: String
    let lastName: String
}

struct PersonStringComparator: SortComparator {
    let keyPath: KeyPath<Person, String> & Sendable
    var order: SortOrder
    init(_ keyPath: KeyPath<Person, String> & Sendable, order: SortOrder = .forward) {
        self.keyPath = keyPath
        self.order = order
    }
    func compare(_ lhs: Person, _ rhs: Person) -> ComparisonResult {
        let options: String.CompareOptions = order == .forward ? [] : [.backwards]
        return lhs[keyPath: keyPath].compare(rhs[keyPath: keyPath], options: options)
    }
}

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        // elsewhere
        var array: [Person] = [
            .init(firstName: "Harpo", lastName: "Marx"),
            .init(firstName: "Groucho", lastName: "Marx"),
            .init(firstName: "Groucho", lastName: "Aardvark")
        ]
        let comparisons: [PersonStringComparator] = [.init(\.lastName), .init(\.firstName)] // ERROR
        array.sort(using: comparisons)
    }
}

/*
 ERROR:
 Type 'KeyPath<Person, String>' does not conform to the 'Sendable' protocol
 Generic class 'KeyPath' does not conform to the 'Sendable' protocol
 */
```

The warning has gone away, but now we can't even compile, on the grounds that the key path is not sendable.

You can try to solve the whole problem by declaring an extension:

    extension KeyPath<Person, String>: @unchecked Sendable {}

But this too elicits a warning:

> Extension declares a conformance of imported type 'KeyPath' to imported protocol 'Sendable'; this will not behave correctly if the owners of 'Swift' introduce this conformance in the future

### Expected behavior

I expect no warning and no compile error. This code compiles and works in Swift 5. It should keep working in Swift 6 given the existence of https://github.com/swiftlang/swift-evolution/blob/main/proposals/0418-inferring-sendable-for-methods.md. It is, I feel, as if that proposal had never been accepted or incorporated into the Swift language.

### Environment

```
swift-driver version: 1.127.14.1 Apple Swift version 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
Target: arm64-apple-macosx26.0
```

**Comment by xedin** [comment]
@mattneub have you tried running this is a recent snapshot? We had a problem with Sendable inference when the context was a global actor isolated (like in this case where ViewController is declared to be `@MainActor`) but this problem should be fixed now and I your example that uses `& Sendable` compiles without warnings for me using a snapshot compiler.

**Comment by mattneub** [comment]
Hi @xedin I'm afraid snapshots don't do us any good. The relevant question is what Xcode does. The problem is not fixed in Xcode 26.1RC.

**Comment by xedin** [comment]
I understand. Unfortunately we cannot guarantee anything about xcode releases that’s why we ask to use a snapshot to verify, if the fix is in the build it would make it into the xcode eventually.

**Comment by xedin** [comment]
@mattneub Could you please give Xcode 26.3 beta a try? I created a sample iOS App and pasted your code (enabled Swift 6 + MainActor default isolation) and the snippet compiled without warnings.

**Comment by mattneub** [comment]
@xedin Agreed! OK to close this one. The code has no warnings / errors, and it actually works too, thus showing that SortComparator is now usable. Thanks for doing that!

**Comment by xedin** [comment]
Thanks for checking so fast!

**Comment by marcomasser** [comment]
I’m not sure if there is a regression or if I’m holding it wrong, but I see the exact same issue with this code (i.e.: a warning and then an error after adding the explicit `Sendable`). I tried the following versions:
- Xcode 26.3 (Swift 6.2.4)
- Xcode 26.4 beta 3 (Swift 6.3)
- Xcode 26.4 beta 3 with the latest snapshot downloaded today (`swift-DEVELOPMENT-SNAPSHOT-2026-03-16-a-osx.pkg`)

I simply copied the code into a new Xcode project. It’s using Swift 6, approachable concurrency is turned, default actor isolation is set to `MainActor`.

Am I missing something?

**Comment by mattneub** [comment]
My bad. I always, always, always forget that a new plain vanilla iOS project does not have Swift 6 turned on.

**Comment by marcomasser** [comment]
Oh, that is an easy mistake to make!

BTW, I opened a forum topic for the issue I’m running into that I guess is related to this one here: https://forums.swift.org/t/mainactor-keypathcomparator-class-error/85447
